### ISSUE TITLE
Code dealing with raw dataset

### ISSUE THREAD

**Issue by mug2mag** [Zhang-xiaokun/CoHHN#1]
@Zhang-xiaokun Great work and thanks for sharing the code.

Could you please share the code dealing with these three raw datasets?

**Comment by Zhang-xiaokun** [comment]
Thank you for attention!
  We have uploaded the codes used to process the datasets.  In the folder 'datasets', 'CoHHNpreprocess.py'.
  For the processing datasets, we mainly refer to the model DHCN and NARM.  You can also watch their codes for references.  We have listed their code's address in the file 'CoHHNpreprocess.py'.
  Good lucky for your research!

**Comment by mug2mag** [comment]
Thanks very much for your reply and the introduced references.
















At 2022-05-19 18:36:19, "Xiaokun Zhang" ***@***.***> wrote:

Thank you for attention!
We have uploaded the codes used to process the datasets. In the folder 'datasets', 'CoHHN.py'.
For the processing datasets, we mainly refer to the model DHCN and NARM. You can also watch their codes for references. We have listed their code's address in the file 'CoHHN.py'.
Good lucky for your research!
