### ISSUE TITLE
Preprocessing for amazon and diginetica datasets

### ISSUE THREAD

**Issue by AkashSrinivasulu** [Zhang-xiaokun/CoHHN#2]
Dear Zhang,

Thank you for sharing your work. I was trying to reproduce the results and found that the CoHHNpreprocess.py file in datasets folder has code for preprocessing only cosmetics dataset. Can you please provide the code for amazon and diginetica datasets as well? Any help is very much appreciated. 

Thank you.

**Comment by Zhang-xiaokun** [comment]
Please refer to the code in 'dataset' for all preprocessing codes.
